### ISSUE TITLE
What is the meaning of token length in Normalization?

### ISSUE THREAD

**Issue by EricLina** [LeapLabTHU/MLLA#1]
Hi there!
Excellent job on your work!
Could you please explain the concept of 'longer token' in this context?
![image](https://github.com/LeapLabTHU/MLLA/assets/60723818/643e9e3d-801f-41b4-bc3b-a72bcf368c13)

**Comment by tian-qing001** [comment]
Hi @EricLina, thanks for your interest in our work. 
In this context, a token $x_i$ is actually a vector in $\mathbb{R}^{1\times d}$ space. We consider a token $x_i$ with larger norm $\Vert x_i \Vert$ to be a longer token. For example, $2x_i$ is longer than $x_i$ when $x_i\neq 0$.

**Comment by EricLina** [comment]
Thanks for your reply.
