### ISSUE TITLE
the ELU activation function

### ISSUE THREAD

**Issue by Journey7331** [LeapLabTHU/MLLA#19]
Hi, @tian-qing001
Thanks for your great work!

Is there any ablation study on the activation function?
And why `q + 1.0` after applying `elu`? ensure `q > 0` for better training? 👀

https://github.com/LeapLabTHU/MLLA/blob/5a1719682cb040ec708fb633ad1379c9eab28576/models/mlla.py#L129-L130

**Comment by tian-qing001** [comment]
Hi @Journey7331, `elu + 1` is a commonly employed kernel function for linear attention, which is proposed in [this work](https://proceedings.mlr.press/v119/katharopoulos20a/katharopoulos20a.pdf).

**Comment by Journey7331** [comment]
Many thanks!
