### ISSUE TITLE
Why remove `focusing_factor`?

### ISSUE THREAD

**Issue by Journey7331** [LeapLabTHU/MLLA#20]
@tian-qing001 Hi, In your paper, I noticed that MLLA is based on the Flatten-Transformer, but the `focusing_factor` or `Focused` LinearAttention has been removed in your implementation code and is not mentioned in the paper. 
Could you provide the reason for this change, or any details on the ablation study that was conducted?

**Comment by tian-qing001** [comment]
Hi @Journey7331, thanks for your question.

There is no direct relationship between this work and FLatten Transformer. This repository shares some similarities with FLatten Transformer as it is also from our lab.

The focused function can improve MLLA's performance. However, it is not the focus of this work. Therefore, we chose to employ the vanilla linear attention in this paper to maintain a clean comparison with Mamba.
