### ISSUE TITLE
About Table 1

### ISSUE THREAD

**Issue by leily578** [LeapLabTHU/MLLA#21]
Thanks for your great work! I have a question about "Table 1: Ablation on the impact of each distinction". How are the input gate and forget gate added in the linear attention? Are they added in the recurrent linear attention form with causal relationship or in the non-causal linear attention?
Looking forward to your reply！

**Comment by tian-qing001** [comment]
Hi @leily578, thanks for your attention to our work.
The input gate is added to the non-causal linear attention mechanism, i.e. $\Delta\odot V$. In contrast, the forget gate is applied to the recurrent linear attention form since it has to be computed recurrently.

**Comment by leily578** [comment]
> Hi @leily578, thanks for your attention to our work. The input gate is added to the non-causal linear attention mechanism, i.e. Δ⊙V. In contrast, the forget gate is applied to the recurrent linear attention form since it has to be computed recurrently.

Thanks to your reply!
