### ISSUE TITLE
关于输入图像尺寸必须为正方形

### ISSUE THREAD

**Issue by ycwsilent** [LeapLabTHU/MLLA#22]
在使用您给出的线性mamba模块时候，我发现在使用正方形图片进行训练时候是正常的，但使用长方形图片就会产生参数量不匹配问题
```
    def forward(self, x):
        print("368行hang--进入MLLAttention-",x.size())
        # torch.Size([1, 40, 256, 256])
        """
        Args:
            x: input features with shape of (B, N, C)
        """
        x = x.reshape((x.size(0), x.size(2) * x.size(3), x.size(1)))
        print("375行hang-",x.size())
        # 375行hang- torch.Size([1, 65536, 40])
        b, n, c = x.shape
        h = int(n ** 0.5)
        w = int(n ** 0.5)
        # self.rope = RoPE(shape=(h, w, self.dim))
        num_heads = self.num_heads
        head_dim = c // num_heads

        qk = self.qk(x).reshape(b, n, 2, c).permute(2, 0, 1, 3)
        q, k, v = qk[0], qk[1], x
        # q, k, v: b, n, c

        q = self.elu(q) + 1.0
        k = self.elu(k) + 1.0
        q_rope = self.rope(q.reshape(b, h, w, c)).reshape(b, n, num_heads, head_dim).permute(0, 2, 1, 3)
        k_rope = self.rope(k.reshape(b, h, w, c)).reshape(b, n, num_heads, head_dim).permute(0, 2, 1, 3)
        q = q.reshape(b, n, num_heads, head_dim).permute(0, 2, 1, 3)
        k = k.reshape(b, n, num_heads, head_dim).permute(0, 2, 1, 3)
        v = v.reshape(b, n, num_heads, head_dim).permute(0, 2, 1, 3)
```

报错为
(torch) root@ehamqjawspcuddxi-snow-659d9d776c-9rt86:/data/coding# python /data/coding/feng/f-Arxiv2024MLLA和MKLA.py
368行hang--进入MLLAttention- torch.Size([1, 40, 400, 600])
375行hang- torch.Size([1, 240000, 40])
Traceback (most recent call last):
  File "/data/coding/feng/f-Arxiv2024MLLA和MKLA.py", line 475, in <module>
    out = model(image)
  File "/data/miniconda/envs/torch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/coding/feng/f-Arxiv2024MLLA和MKLA.py", line 390, in forward
    q_rope = self.rope(q.reshape(b, h, w, c)).reshape(b, n, num_heads, head_dim).permute(0, 2, 1, 3)
RuntimeError: shape '[1, 489, 489, 40]' is invalid for input of size 9600000
问题似乎出现在对n开根号后强制变成整数,但是后面参数量又对不上造成的，请问有能够适应不同大小尺寸输入的版本吗

**Comment by tian-qing001** [comment]
Hi @ycwsilent, thanks for your interest in our work.
I think maybe you can update these two lines to meet the shape of your input.
```
        h = int(n ** 0.5)  # height of the input
        w = int(n ** 0.5)  # width of the input
```

**Comment by gaoGyr** [comment]
我也出现这个问题了，我的训练集没有问题，但是验证集不行直接报这个错误，然后我对其进行了如下修改把rect修改如下
return build_yolo_dataset(self.args, img_path, batch, self.data, mode=mode, rect=False, stride=gs)
然后又报了这个错误
    kv = (k_rope.transpose(-2, -1) * (n ** -0.5)) @ (v * (n ** -0.5))
RuntimeError: expected scalar type Half but found Float

**Comment by ycwsilent** [comment]
> 我也出现这个问题了，我的训练集没有问题，但是验证集不行直接报这个错误，然后我对其进行了如下修改把rect修改如下 return build_yolo_dataset(self.args, img_path, batch, self.data, mode=mode, rect=False, stride=gs) 然后又报了这个错误 kv = (k_rope.transpose(-2, -1) * (n ** -0.5)) @ (v * (n ** -0.5)) RuntimeError: expected scalar type Half but found Float

是因为这里将输入转为正方形了；但是如果这里不管，直接使用原输入的长和宽，在另一个函数里面旋转也会报错；尚未解决，如果您有解决方法，方便分享吗

**Comment by gaoGyr** [comment]
> > 我也出现这个问题了，我的训练集没有问题，但是验证集不行直接报这个错误，然后我对其进行了如下修改把rect修改如下 return build_yolo_dataset(self.args, img_path, batch, self.data, mode=mode, rect=False, stride=gs) 然后又报了这个错误 kv = (k_rope.transpose(-2, -1) * (n ** -0.5)) @ (v * (n ** -0.5)) RuntimeError: expected scalar type Half but found Float
> 
> 是因为这里将输入转为正方形了；但是如果这里不管，直接使用原输入的长和宽，在另一个函数里面旋转也会报错；尚未解决，如果您有解决方法，方便分享吗

也是尚未解决，他这里开根号，会导致不规则有误差，最后参数难以匹配

**Comment by tian-qing001** [comment]
@ycwsilent @gaoGyr 
Thanks for using our method.
Your problem can be fixed with modifications to a few lines. Please try the code below.
```python
class LinearAttention(nn.Module):
    r""" Linear Attention with LePE and RoPE.

    Args:
        dim (int): Number of input channels.
        num_heads (int): Number of attention heads.
        qkv_bias (bool, optional):  If True, add a learnable bias to query, key, value. Default: True
    """

    def __init__(self, dim, num_heads, qkv_bias=True, **kwargs):

        super().__init__()
        self.dim = dim
        self.num_heads = num_heads
        self.qk = nn.Linear(dim, dim * 2, bias=qkv_bias)
        self.elu = nn.ELU()
        self.lepe = nn.Conv2d(dim, dim, 3, padding=1, groups=dim)

    def forward(self, x, h, w):
        """
        Args:
            x: input features with shape of (B, N, C)
        """
        b, n, c = x.shape
        assert h * w == n
        num_heads = self.num_heads
        head_dim = c // num_heads

        qk = self.qk(x).reshape(b, n, 2, c).permute(2, 0, 1, 3)
        q, k, v = qk[0], qk[1], x
        # q, k, v: b, n, c

        q = self.elu(q) + 1.0
        k = self.elu(k) + 1.0
        rope = RoPE(shape=(h, w, c))
        q_rope = rope(q.reshape(b, h, w, c)).reshape(b, n, num_heads, head_dim).permute(0, 2, 1, 3)
        k_rope = rope(k.reshape(b, h, w, c)).reshape(b, n, num_heads, head_dim).permute(0, 2, 1, 3)
        q = q.reshape(b, n, num_heads, head_dim).permute(0, 2, 1, 3)
        k = k.reshape(b, n, num_heads, head_dim).permute(0, 2, 1, 3)
        v = v.reshape(b, n, num_heads, head_dim).permute(0, 2, 1, 3)

        z = 1 / (q @ k.mean(dim=-2, keepdim=True).transpose(-2, -1) + 1e-6)
        kv = (k_rope.transpose(-2, -1) * (n ** -0.5)) @ (v * (n ** -0.5))
        x = q_rope @ kv * z

        x = x.transpose(1, 2).reshape(b, n, c)
        v = v.transpose(1, 2).reshape(b, h, w, c).permute(0, 3, 1, 2)
        x = x + self.lepe(v).permute(0, 2, 3, 1).reshape(b, n, c)

        return x
```

**Comment by lxymyy** [comment]
> ```python
> n ** -0.5
> ```

请问这个问题解决了吗

**Comment by duxiying0369** [comment]
> 在使用您给出的线性mamba模块时候，我发现在使用正方形图片进行训练时候是正常的，但使用长方形图片就会产生参数量不匹配问题
> 
> ```
>     def forward(self, x):
>         print("368行hang--进入MLLAttention-",x.size())
>         # torch.Size([1, 40, 256, 256])
>         """
>         Args:
>             x: input features with shape of (B, N, C)
>         """
>         x = x.reshape((x.size(0), x.size(2) * x.size(3), x.size(1)))
>         print("375行hang-",x.size())
>         # 375行hang- torch.Size([1, 65536, 40])
>         b, n, c = x.shape
>         h = int(n ** 0.5)
>         w = int(n ** 0.5)
>         # self.rope = RoPE(shape=(h, w, self.dim))
>         num_heads = self.num_heads
>         head_dim = c // num_heads
> 
>         qk = self.qk(x).reshape(b, n, 2, c).permute(2, 0, 1, 3)
>         q, k, v = qk[0], qk[1], x
>         # q, k, v: b, n, c
> 
>         q = self.elu(q) + 1.0
>         k = self.elu(k) + 1.0
>         q_rope = self.rope(q.reshape(b, h, w, c)).reshape(b, n, num_heads, head_dim).permute(0, 2, 1, 3)
>         k_rope = self.rope(k.reshape(b, h, w, c)).reshape(b, n, num_heads, head_dim).permute(0, 2, 1, 3)
>         q = q.reshape(b, n, num_heads, head_dim).permute(0, 2, 1, 3)
>         k = k.reshape(b, n, num_heads, head_dim).permute(0, 2, 1, 3)
>         v = v.reshape(b, n, num_heads, head_dim).permute(0, 2, 1, 3)
> ```
> 
> 报错为 (torch) root@ehamqjawspcuddxi-snow-659d9d776c-9rt86:/data/coding# python /data/coding/feng/f-Arxiv2024MLLA和MKLA.py 368行hang--进入MLLAttention- torch.Size([1, 40, 400, 600]) 375行hang- torch.Size([1, 240000, 40]) Traceback (most recent call last): File "/data/coding/feng/f-Arxiv2024MLLA和MKLA.py", line 475, in out = model(image) File "/data/miniconda/envs/torch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl return forward_call(*input, **kwargs) File "/data/coding/feng/f-Arxiv2024MLLA和MKLA.py", line 390, in forward q_rope = self.rope(q.reshape(b, h, w, c)).reshape(b, n, num_heads, head_dim).permute(0, 2, 1, 3) RuntimeError: shape '[1, 489, 489, 40]' is invalid for input of size 9600000 问题似乎出现在对n开根号后强制变成整数,但是后面参数量又对不上造成的，请问有能够适应不同大小尺寸输入的版本吗

请问这个问题解决了吗，我按作者回复里的方法修改后还是不行
