### ISSUE TITLE
runing Error

### ISSUE THREAD

**Issue by gaoGyr** [LeapLabTHU/MLLA#23]
![EHC W}GB(~1KCF@I`TB}M](https://github.com/user-attachments/assets/56bbc8b9-9fd2-4268-9da6-1be0a1a16b04)

training appears this problem

**Comment by tian-qing001** [comment]
Hi @gaoGyr, thanks for trying our method. We already fixed this in [the previous commit](https://github.com/LeapLabTHU/MLLA/commit/5a1719682cb040ec708fb633ad1379c9eab28576). Please update your code~
