### ISSUE TITLE
runing errors

### ISSUE THREAD

**Issue by gaoGyr** [LeapLabTHU/MLLA#24]
我按照您的回答修改如下解决了Copmlex half的问题，
 if x.dtype != torch.float32:
            x = x.to(torch.float32)
我的训练集没有问题，但是验证集不行直接报这个错误，然后我对其进行了如下修改把rect修改如下
return build_yolo_dataset(self.args, img_path, batch, self.data, mode=mode, rect=False, stride=gs)
然后又报了这个错误
kv = (k_rope.transpose(-2, -1) * (n ** -0.5)) @ (v * (n ** -0.5))
RuntimeError: expected scalar type Half but found Float

**Comment by tian-qing001** [comment]
Please refer to https://github.com/LeapLabTHU/MLLA/issues/22#issuecomment-2285595729.
