### ISSUE TITLE
About the calculation of the number of parameters

### ISSUE THREAD

**Issue by Mrrfu** [LeapLabTHU/MLLA#30]
![屏幕截图 2024-10-23 194147](https://github.com/user-attachments/assets/4c871a7b-426e-47df-bede-bd14bbd7d34f)
 I used your code to build the tiny model, but I calculated the number of parameters as 55M instead of the 25M you wrote in the paper. How do you calculate the parameters? Looking forward to your answer！

**Comment by tian-qing001** [comment]
Hi @Mrrfu, I believe there is something wrong. The dimensions of the four stages in our tiny model are 64, 128, 256, 512. However, your settings are 96, 192, 384, 768. Please refer to [mlla_t.yaml](https://github.com/LeapLabTHU/MLLA/blob/08d31683699e0740f797d9173c829c8675e743e8/cfgs/mlla_t.yaml).
